### PR TITLE
Some corrections

### PR DESCRIPTION
**Pull request by ericbrasiln**
I made some corrections in the README.md

Next week I'll create a issue proposing you to create a Project in GH to help to improve your studies.

### CODE REVIEW

**Comment by priscilavalverdes** [comment]
> I made some corrections in the README.md
> 
> Next week I'll create a issue proposing you to create a Project in GH to help to improve your studies.

@ericbrasiln , I didin't understend. You are proposing one model project or you are talking for i create one? I created, but is incomplete.

**Comment by ericbrasiln** [comment]
Where did you create the Project? Send me the link, please? I couldn't find it in your profile page.

**Comment by priscilavalverdes** [comment]
@ericbrasiln, here (https://github.com/users/priscilavalverdes/projects/1)

**Comment by ericbrasiln** [comment]
> @ericbrasiln, here (https://github.com/users/priscilavalverdes/projects/1)

image
Is it private?

**Comment by priscilavalverdes** [comment]
> > @ericbrasiln, here (https://github.com/users/priscilavalverdes/projects/1)
> 
> image Is it private?

Put on public now. I dont know what the project repositories publics stayed private.

**Pull request merged**
